/**
 * @file userProgram.c
 * @author Pöschl Rene
 *
 * The main user program
 *
 * Copyright 2017 Pöschl Rene Copyright and related rights are licensed under the Solderpad Hardware License,
 * Version 0.51 (the “License”); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://solderpad.org/licenses/SHL-0.51.
 * Unless required by applicable law or agreed to in writing, software,
 * hardware and materials distributed under this License is distributed on an “AS IS” BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 */

#ifndef UNIT_TESTING
// standard libraries
#include <stdbool.h>
#include <stdlib.h>

// CubeMX labels
#include <main.h>
#include <stdint.h>

// HAL / Newlib
#include <diag/Trace.h>
#include <stm32f4xx_hal.h>

#include "../communication/bms_terminal.h"
#include "../communication/bms_can.h"
#include "../external_systems/relay_manager.h"
#include "../fault_management/battery_protector.h"

#include "statemachine.h"

#include "timer.h"


uint32_t max_time_per_loop;



void userInit() {
  initBMScan();
}

// Initializing of the HW is done with the code generated by CubeMX (See CubeMX_Master_HWv6p/Src)
void userLoop() {

  // Toggle LED to show we are still alive
  //TERA_LED_toggle(&led1);
  uint32_t start_tick = HAL_GetTick();
  statemachine_run();
  relayManager_run();

  uint32_t time_elapsed = HAL_GetTick() - start_tick;
  //if(time_elapsed > max_time_per_loop){
    max_time_per_loop = time_elapsed;
  //}
  //test_status = HAL_ADC_Start_DMA(&hadc1, (uint32_t*)adc1_storage, ADC1_NUM_CHANNELS);
  //TI_BQ76PL536_readStatusRegisters(1);
  // Wait a little
  HAL_Delay(100);

}

#endif // UNIT_TESTING
